'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class DataSetVehicles
    Inherits DataSet
    
    Private tableVehicleInfo As VehicleInfoDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("VehicleInfo")) Is Nothing) Then
                Me.Tables.Add(New VehicleInfoDataTable(ds.Tables("VehicleInfo")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property VehicleInfo As VehicleInfoDataTable
        Get
            Return Me.tableVehicleInfo
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As DataSetVehicles = CType(MyBase.Clone,DataSetVehicles)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("VehicleInfo")) Is Nothing) Then
            Me.Tables.Add(New VehicleInfoDataTable(ds.Tables("VehicleInfo")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableVehicleInfo = CType(Me.Tables("VehicleInfo"),VehicleInfoDataTable)
        If (Not (Me.tableVehicleInfo) Is Nothing) Then
            Me.tableVehicleInfo.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "DataSetVehicles"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/DataSetVehicles.xsd"
        Me.Locale = New System.Globalization.CultureInfo("zh-CN")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableVehicleInfo = New VehicleInfoDataTable
        Me.Tables.Add(Me.tableVehicleInfo)
    End Sub
    
    Private Function ShouldSerializeVehicleInfo() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub VehicleInfoRowChangeEventHandler(ByVal sender As Object, ByVal e As VehicleInfoRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class VehicleInfoDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnLocation As DataColumn
        
        Private columnVehicleNO As DataColumn
        
        Private columnLocationDescription As DataColumn
        
        Friend Sub New()
            MyBase.New("VehicleInfo")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property LocationColumn As DataColumn
            Get
                Return Me.columnLocation
            End Get
        End Property
        
        Friend ReadOnly Property VehicleNOColumn As DataColumn
            Get
                Return Me.columnVehicleNO
            End Get
        End Property
        
        Friend ReadOnly Property LocationDescriptionColumn As DataColumn
            Get
                Return Me.columnLocationDescription
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As VehicleInfoRow
            Get
                Return CType(Me.Rows(index),VehicleInfoRow)
            End Get
        End Property
        
        Public Event VehicleInfoRowChanged As VehicleInfoRowChangeEventHandler
        
        Public Event VehicleInfoRowChanging As VehicleInfoRowChangeEventHandler
        
        Public Event VehicleInfoRowDeleted As VehicleInfoRowChangeEventHandler
        
        Public Event VehicleInfoRowDeleting As VehicleInfoRowChangeEventHandler
        
        Public Overloads Sub AddVehicleInfoRow(ByVal row As VehicleInfoRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddVehicleInfoRow(ByVal Location As String, ByVal LocationDescription As String) As VehicleInfoRow
            Dim rowVehicleInfoRow As VehicleInfoRow = CType(Me.NewRow,VehicleInfoRow)
            rowVehicleInfoRow.ItemArray = New Object() {Location, Nothing, LocationDescription}
            Me.Rows.Add(rowVehicleInfoRow)
            Return rowVehicleInfoRow
        End Function
        
        Public Function FindByVehicleNO(ByVal VehicleNO As Integer) As VehicleInfoRow
            Return CType(Me.Rows.Find(New Object() {VehicleNO}),VehicleInfoRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As VehicleInfoDataTable = CType(MyBase.Clone,VehicleInfoDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New VehicleInfoDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnLocation = Me.Columns("Location")
            Me.columnVehicleNO = Me.Columns("VehicleNO")
            Me.columnLocationDescription = Me.Columns("LocationDescription")
        End Sub
        
        Private Sub InitClass()
            Me.columnLocation = New DataColumn("Location", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnLocation)
            Me.columnVehicleNO = New DataColumn("VehicleNO", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnVehicleNO)
            Me.columnLocationDescription = New DataColumn("LocationDescription", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnLocationDescription)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columnVehicleNO}, true))
            Me.columnVehicleNO.AutoIncrement = true
            Me.columnVehicleNO.AllowDBNull = false
            Me.columnVehicleNO.Unique = true
        End Sub
        
        Public Function NewVehicleInfoRow() As VehicleInfoRow
            Return CType(Me.NewRow,VehicleInfoRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New VehicleInfoRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(VehicleInfoRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.VehicleInfoRowChangedEvent) Is Nothing) Then
                RaiseEvent VehicleInfoRowChanged(Me, New VehicleInfoRowChangeEvent(CType(e.Row,VehicleInfoRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.VehicleInfoRowChangingEvent) Is Nothing) Then
                RaiseEvent VehicleInfoRowChanging(Me, New VehicleInfoRowChangeEvent(CType(e.Row,VehicleInfoRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.VehicleInfoRowDeletedEvent) Is Nothing) Then
                RaiseEvent VehicleInfoRowDeleted(Me, New VehicleInfoRowChangeEvent(CType(e.Row,VehicleInfoRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.VehicleInfoRowDeletingEvent) Is Nothing) Then
                RaiseEvent VehicleInfoRowDeleting(Me, New VehicleInfoRowChangeEvent(CType(e.Row,VehicleInfoRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveVehicleInfoRow(ByVal row As VehicleInfoRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class VehicleInfoRow
        Inherits DataRow
        
        Private tableVehicleInfo As VehicleInfoDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableVehicleInfo = CType(Me.Table,VehicleInfoDataTable)
        End Sub
        
        Public Property Location As String
            Get
                Try 
                    Return CType(Me(Me.tableVehicleInfo.LocationColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("无法获取值，因为它是 DBNull。", e)
                End Try
            End Get
            Set
                Me(Me.tableVehicleInfo.LocationColumn) = value
            End Set
        End Property
        
        Public Property VehicleNO As Integer
            Get
                Return CType(Me(Me.tableVehicleInfo.VehicleNOColumn),Integer)
            End Get
            Set
                Me(Me.tableVehicleInfo.VehicleNOColumn) = value
            End Set
        End Property
        
        Public Property LocationDescription As String
            Get
                Try 
                    Return CType(Me(Me.tableVehicleInfo.LocationDescriptionColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("无法获取值，因为它是 DBNull。", e)
                End Try
            End Get
            Set
                Me(Me.tableVehicleInfo.LocationDescriptionColumn) = value
            End Set
        End Property
        
        Public Function IsLocationNull() As Boolean
            Return Me.IsNull(Me.tableVehicleInfo.LocationColumn)
        End Function
        
        Public Sub SetLocationNull()
            Me(Me.tableVehicleInfo.LocationColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsLocationDescriptionNull() As Boolean
            Return Me.IsNull(Me.tableVehicleInfo.LocationDescriptionColumn)
        End Function
        
        Public Sub SetLocationDescriptionNull()
            Me(Me.tableVehicleInfo.LocationDescriptionColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class VehicleInfoRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As VehicleInfoRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As VehicleInfoRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As VehicleInfoRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
