'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class DataSetGPS
    Inherits DataSet
    
    Private tableTranPlan As TranPlanDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("TranPlan")) Is Nothing) Then
                Me.Tables.Add(New TranPlanDataTable(ds.Tables("TranPlan")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property TranPlan As TranPlanDataTable
        Get
            Return Me.tableTranPlan
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As DataSetGPS = CType(MyBase.Clone,DataSetGPS)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("TranPlan")) Is Nothing) Then
            Me.Tables.Add(New TranPlanDataTable(ds.Tables("TranPlan")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableTranPlan = CType(Me.Tables("TranPlan"),TranPlanDataTable)
        If (Not (Me.tableTranPlan) Is Nothing) Then
            Me.tableTranPlan.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "DataSetGPS"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/DataSetGPS.xsd"
        Me.Locale = New System.Globalization.CultureInfo("zh-CN")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableTranPlan = New TranPlanDataTable
        Me.Tables.Add(Me.tableTranPlan)
    End Sub
    
    Private Function ShouldSerializeTranPlan() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub TranPlanRowChangeEventHandler(ByVal sender As Object, ByVal e As TranPlanRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class TranPlanDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnVehicleNO As DataColumn
        
        Private columnExpr1 As DataColumn
        
        Private columnTranPlanNO As DataColumn
        
        Private columnTranOrderFormNO As DataColumn
        
        Private columnLocation As DataColumn
        
        Private columnLocationDescription As DataColumn
        
        Private columnTransitRoute As DataColumn
        
        Private columnDestination As DataColumn
        
        Friend Sub New()
            MyBase.New("TranPlan")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property VehicleNOColumn As DataColumn
            Get
                Return Me.columnVehicleNO
            End Get
        End Property
        
        Friend ReadOnly Property Expr1Column As DataColumn
            Get
                Return Me.columnExpr1
            End Get
        End Property
        
        Friend ReadOnly Property TranPlanNOColumn As DataColumn
            Get
                Return Me.columnTranPlanNO
            End Get
        End Property
        
        Friend ReadOnly Property TranOrderFormNOColumn As DataColumn
            Get
                Return Me.columnTranOrderFormNO
            End Get
        End Property
        
        Friend ReadOnly Property LocationColumn As DataColumn
            Get
                Return Me.columnLocation
            End Get
        End Property
        
        Friend ReadOnly Property LocationDescriptionColumn As DataColumn
            Get
                Return Me.columnLocationDescription
            End Get
        End Property
        
        Friend ReadOnly Property TransitRouteColumn As DataColumn
            Get
                Return Me.columnTransitRoute
            End Get
        End Property
        
        Friend ReadOnly Property DestinationColumn As DataColumn
            Get
                Return Me.columnDestination
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As TranPlanRow
            Get
                Return CType(Me.Rows(index),TranPlanRow)
            End Get
        End Property
        
        Public Event TranPlanRowChanged As TranPlanRowChangeEventHandler
        
        Public Event TranPlanRowChanging As TranPlanRowChangeEventHandler
        
        Public Event TranPlanRowDeleted As TranPlanRowChangeEventHandler
        
        Public Event TranPlanRowDeleting As TranPlanRowChangeEventHandler
        
        Public Overloads Sub AddTranPlanRow(ByVal row As TranPlanRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddTranPlanRow(ByVal Expr1 As Integer, ByVal TranOrderFormNO As Integer, ByVal Location As String, ByVal LocationDescription As String, ByVal TransitRoute As String, ByVal Destination As String) As TranPlanRow
            Dim rowTranPlanRow As TranPlanRow = CType(Me.NewRow,TranPlanRow)
            rowTranPlanRow.ItemArray = New Object() {Nothing, Expr1, Nothing, TranOrderFormNO, Location, LocationDescription, TransitRoute, Destination}
            Me.Rows.Add(rowTranPlanRow)
            Return rowTranPlanRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As TranPlanDataTable = CType(MyBase.Clone,TranPlanDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New TranPlanDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnVehicleNO = Me.Columns("VehicleNO")
            Me.columnExpr1 = Me.Columns("Expr1")
            Me.columnTranPlanNO = Me.Columns("TranPlanNO")
            Me.columnTranOrderFormNO = Me.Columns("TranOrderFormNO")
            Me.columnLocation = Me.Columns("Location")
            Me.columnLocationDescription = Me.Columns("LocationDescription")
            Me.columnTransitRoute = Me.Columns("TransitRoute")
            Me.columnDestination = Me.Columns("Destination")
        End Sub
        
        Private Sub InitClass()
            Me.columnVehicleNO = New DataColumn("VehicleNO", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnVehicleNO)
            Me.columnExpr1 = New DataColumn("Expr1", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnExpr1)
            Me.columnTranPlanNO = New DataColumn("TranPlanNO", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTranPlanNO)
            Me.columnTranOrderFormNO = New DataColumn("TranOrderFormNO", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTranOrderFormNO)
            Me.columnLocation = New DataColumn("Location", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnLocation)
            Me.columnLocationDescription = New DataColumn("LocationDescription", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnLocationDescription)
            Me.columnTransitRoute = New DataColumn("TransitRoute", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTransitRoute)
            Me.columnDestination = New DataColumn("Destination", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDestination)
            Me.columnVehicleNO.AutoIncrement = true
            Me.columnTranPlanNO.AutoIncrement = true
        End Sub
        
        Public Function NewTranPlanRow() As TranPlanRow
            Return CType(Me.NewRow,TranPlanRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New TranPlanRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(TranPlanRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.TranPlanRowChangedEvent) Is Nothing) Then
                RaiseEvent TranPlanRowChanged(Me, New TranPlanRowChangeEvent(CType(e.Row,TranPlanRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.TranPlanRowChangingEvent) Is Nothing) Then
                RaiseEvent TranPlanRowChanging(Me, New TranPlanRowChangeEvent(CType(e.Row,TranPlanRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.TranPlanRowDeletedEvent) Is Nothing) Then
                RaiseEvent TranPlanRowDeleted(Me, New TranPlanRowChangeEvent(CType(e.Row,TranPlanRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.TranPlanRowDeletingEvent) Is Nothing) Then
                RaiseEvent TranPlanRowDeleting(Me, New TranPlanRowChangeEvent(CType(e.Row,TranPlanRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveTranPlanRow(ByVal row As TranPlanRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class TranPlanRow
        Inherits DataRow
        
        Private tableTranPlan As TranPlanDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableTranPlan = CType(Me.Table,TranPlanDataTable)
        End Sub
        
        Public Property VehicleNO As Integer
            Get
                Try 
                    Return CType(Me(Me.tableTranPlan.VehicleNOColumn),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("无法获取值，因为它是 DBNull。", e)
                End Try
            End Get
            Set
                Me(Me.tableTranPlan.VehicleNOColumn) = value
            End Set
        End Property
        
        Public Property Expr1 As Integer
            Get
                Try 
                    Return CType(Me(Me.tableTranPlan.Expr1Column),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("无法获取值，因为它是 DBNull。", e)
                End Try
            End Get
            Set
                Me(Me.tableTranPlan.Expr1Column) = value
            End Set
        End Property
        
        Public Property TranPlanNO As Integer
            Get
                Try 
                    Return CType(Me(Me.tableTranPlan.TranPlanNOColumn),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("无法获取值，因为它是 DBNull。", e)
                End Try
            End Get
            Set
                Me(Me.tableTranPlan.TranPlanNOColumn) = value
            End Set
        End Property
        
        Public Property TranOrderFormNO As Integer
            Get
                Try 
                    Return CType(Me(Me.tableTranPlan.TranOrderFormNOColumn),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("无法获取值，因为它是 DBNull。", e)
                End Try
            End Get
            Set
                Me(Me.tableTranPlan.TranOrderFormNOColumn) = value
            End Set
        End Property
        
        Public Property Location As String
            Get
                Try 
                    Return CType(Me(Me.tableTranPlan.LocationColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("无法获取值，因为它是 DBNull。", e)
                End Try
            End Get
            Set
                Me(Me.tableTranPlan.LocationColumn) = value
            End Set
        End Property
        
        Public Property LocationDescription As String
            Get
                Try 
                    Return CType(Me(Me.tableTranPlan.LocationDescriptionColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("无法获取值，因为它是 DBNull。", e)
                End Try
            End Get
            Set
                Me(Me.tableTranPlan.LocationDescriptionColumn) = value
            End Set
        End Property
        
        Public Property TransitRoute As String
            Get
                Try 
                    Return CType(Me(Me.tableTranPlan.TransitRouteColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("无法获取值，因为它是 DBNull。", e)
                End Try
            End Get
            Set
                Me(Me.tableTranPlan.TransitRouteColumn) = value
            End Set
        End Property
        
        Public Property Destination As String
            Get
                Try 
                    Return CType(Me(Me.tableTranPlan.DestinationColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("无法获取值，因为它是 DBNull。", e)
                End Try
            End Get
            Set
                Me(Me.tableTranPlan.DestinationColumn) = value
            End Set
        End Property
        
        Public Function IsVehicleNONull() As Boolean
            Return Me.IsNull(Me.tableTranPlan.VehicleNOColumn)
        End Function
        
        Public Sub SetVehicleNONull()
            Me(Me.tableTranPlan.VehicleNOColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsExpr1Null() As Boolean
            Return Me.IsNull(Me.tableTranPlan.Expr1Column)
        End Function
        
        Public Sub SetExpr1Null()
            Me(Me.tableTranPlan.Expr1Column) = System.Convert.DBNull
        End Sub
        
        Public Function IsTranPlanNONull() As Boolean
            Return Me.IsNull(Me.tableTranPlan.TranPlanNOColumn)
        End Function
        
        Public Sub SetTranPlanNONull()
            Me(Me.tableTranPlan.TranPlanNOColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsTranOrderFormNONull() As Boolean
            Return Me.IsNull(Me.tableTranPlan.TranOrderFormNOColumn)
        End Function
        
        Public Sub SetTranOrderFormNONull()
            Me(Me.tableTranPlan.TranOrderFormNOColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsLocationNull() As Boolean
            Return Me.IsNull(Me.tableTranPlan.LocationColumn)
        End Function
        
        Public Sub SetLocationNull()
            Me(Me.tableTranPlan.LocationColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsLocationDescriptionNull() As Boolean
            Return Me.IsNull(Me.tableTranPlan.LocationDescriptionColumn)
        End Function
        
        Public Sub SetLocationDescriptionNull()
            Me(Me.tableTranPlan.LocationDescriptionColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsTransitRouteNull() As Boolean
            Return Me.IsNull(Me.tableTranPlan.TransitRouteColumn)
        End Function
        
        Public Sub SetTransitRouteNull()
            Me(Me.tableTranPlan.TransitRouteColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDestinationNull() As Boolean
            Return Me.IsNull(Me.tableTranPlan.DestinationColumn)
        End Function
        
        Public Sub SetDestinationNull()
            Me(Me.tableTranPlan.DestinationColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class TranPlanRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As TranPlanRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As TranPlanRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As TranPlanRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
