'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class DataSetTranPlan
    Inherits DataSet
    
    Private tableTranPlan As TranPlanDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("TranPlan")) Is Nothing) Then
                Me.Tables.Add(New TranPlanDataTable(ds.Tables("TranPlan")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property TranPlan As TranPlanDataTable
        Get
            Return Me.tableTranPlan
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As DataSetTranPlan = CType(MyBase.Clone,DataSetTranPlan)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("TranPlan")) Is Nothing) Then
            Me.Tables.Add(New TranPlanDataTable(ds.Tables("TranPlan")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableTranPlan = CType(Me.Tables("TranPlan"),TranPlanDataTable)
        If (Not (Me.tableTranPlan) Is Nothing) Then
            Me.tableTranPlan.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "DataSetTranPlan"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/DataSetTranPlan.xsd"
        Me.Locale = New System.Globalization.CultureInfo("zh-CN")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableTranPlan = New TranPlanDataTable
        Me.Tables.Add(Me.tableTranPlan)
    End Sub
    
    Private Function ShouldSerializeTranPlan() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub TranPlanRowChangeEventHandler(ByVal sender As Object, ByVal e As TranPlanRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class TranPlanDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnCmpltTime As DataColumn
        
        Private columnDepartureTime As DataColumn
        
        Private columnDestination As DataColumn
        
        Private columnInitialPlace As DataColumn
        
        Private columnNote As DataColumn
        
        Private columnTranCost As DataColumn
        
        Private columnTranOrderFormNO As DataColumn
        
        Private columnTranPlanNO As DataColumn
        
        Private columnTransitRoute As DataColumn
        
        Private columnVehicleNO As DataColumn
        
        Friend Sub New()
            MyBase.New("TranPlan")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property CmpltTimeColumn As DataColumn
            Get
                Return Me.columnCmpltTime
            End Get
        End Property
        
        Friend ReadOnly Property DepartureTimeColumn As DataColumn
            Get
                Return Me.columnDepartureTime
            End Get
        End Property
        
        Friend ReadOnly Property DestinationColumn As DataColumn
            Get
                Return Me.columnDestination
            End Get
        End Property
        
        Friend ReadOnly Property InitialPlaceColumn As DataColumn
            Get
                Return Me.columnInitialPlace
            End Get
        End Property
        
        Friend ReadOnly Property NoteColumn As DataColumn
            Get
                Return Me.columnNote
            End Get
        End Property
        
        Friend ReadOnly Property TranCostColumn As DataColumn
            Get
                Return Me.columnTranCost
            End Get
        End Property
        
        Friend ReadOnly Property TranOrderFormNOColumn As DataColumn
            Get
                Return Me.columnTranOrderFormNO
            End Get
        End Property
        
        Friend ReadOnly Property TranPlanNOColumn As DataColumn
            Get
                Return Me.columnTranPlanNO
            End Get
        End Property
        
        Friend ReadOnly Property TransitRouteColumn As DataColumn
            Get
                Return Me.columnTransitRoute
            End Get
        End Property
        
        Friend ReadOnly Property VehicleNOColumn As DataColumn
            Get
                Return Me.columnVehicleNO
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As TranPlanRow
            Get
                Return CType(Me.Rows(index),TranPlanRow)
            End Get
        End Property
        
        Public Event TranPlanRowChanged As TranPlanRowChangeEventHandler
        
        Public Event TranPlanRowChanging As TranPlanRowChangeEventHandler
        
        Public Event TranPlanRowDeleted As TranPlanRowChangeEventHandler
        
        Public Event TranPlanRowDeleting As TranPlanRowChangeEventHandler
        
        Public Overloads Sub AddTranPlanRow(ByVal row As TranPlanRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddTranPlanRow(ByVal CmpltTime As String, ByVal DepartureTime As String, ByVal Destination As String, ByVal InitialPlace As String, ByVal Note As String, ByVal TranCost As Integer, ByVal TranOrderFormNO As Integer, ByVal TransitRoute As String, ByVal VehicleNO As Integer) As TranPlanRow
            Dim rowTranPlanRow As TranPlanRow = CType(Me.NewRow,TranPlanRow)
            rowTranPlanRow.ItemArray = New Object() {CmpltTime, DepartureTime, Destination, InitialPlace, Note, TranCost, TranOrderFormNO, Nothing, TransitRoute, VehicleNO}
            Me.Rows.Add(rowTranPlanRow)
            Return rowTranPlanRow
        End Function
        
        Public Function FindByTranOrderFormNOTranPlanNOVehicleNO(ByVal TranOrderFormNO As Integer, ByVal TranPlanNO As Integer, ByVal VehicleNO As Integer) As TranPlanRow
            Return CType(Me.Rows.Find(New Object() {TranOrderFormNO, TranPlanNO, VehicleNO}),TranPlanRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As TranPlanDataTable = CType(MyBase.Clone,TranPlanDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New TranPlanDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnCmpltTime = Me.Columns("CmpltTime")
            Me.columnDepartureTime = Me.Columns("DepartureTime")
            Me.columnDestination = Me.Columns("Destination")
            Me.columnInitialPlace = Me.Columns("InitialPlace")
            Me.columnNote = Me.Columns("Note")
            Me.columnTranCost = Me.Columns("TranCost")
            Me.columnTranOrderFormNO = Me.Columns("TranOrderFormNO")
            Me.columnTranPlanNO = Me.Columns("TranPlanNO")
            Me.columnTransitRoute = Me.Columns("TransitRoute")
            Me.columnVehicleNO = Me.Columns("VehicleNO")
        End Sub
        
        Private Sub InitClass()
            Me.columnCmpltTime = New DataColumn("CmpltTime", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCmpltTime)
            Me.columnDepartureTime = New DataColumn("DepartureTime", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDepartureTime)
            Me.columnDestination = New DataColumn("Destination", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDestination)
            Me.columnInitialPlace = New DataColumn("InitialPlace", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnInitialPlace)
            Me.columnNote = New DataColumn("Note", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNote)
            Me.columnTranCost = New DataColumn("TranCost", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTranCost)
            Me.columnTranOrderFormNO = New DataColumn("TranOrderFormNO", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTranOrderFormNO)
            Me.columnTranPlanNO = New DataColumn("TranPlanNO", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTranPlanNO)
            Me.columnTransitRoute = New DataColumn("TransitRoute", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnTransitRoute)
            Me.columnVehicleNO = New DataColumn("VehicleNO", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnVehicleNO)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columnTranOrderFormNO, Me.columnTranPlanNO, Me.columnVehicleNO}, true))
            Me.columnTranOrderFormNO.AllowDBNull = false
            Me.columnTranPlanNO.AutoIncrement = true
            Me.columnTranPlanNO.AllowDBNull = false
            Me.columnVehicleNO.AllowDBNull = false
        End Sub
        
        Public Function NewTranPlanRow() As TranPlanRow
            Return CType(Me.NewRow,TranPlanRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New TranPlanRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(TranPlanRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.TranPlanRowChangedEvent) Is Nothing) Then
                RaiseEvent TranPlanRowChanged(Me, New TranPlanRowChangeEvent(CType(e.Row,TranPlanRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.TranPlanRowChangingEvent) Is Nothing) Then
                RaiseEvent TranPlanRowChanging(Me, New TranPlanRowChangeEvent(CType(e.Row,TranPlanRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.TranPlanRowDeletedEvent) Is Nothing) Then
                RaiseEvent TranPlanRowDeleted(Me, New TranPlanRowChangeEvent(CType(e.Row,TranPlanRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.TranPlanRowDeletingEvent) Is Nothing) Then
                RaiseEvent TranPlanRowDeleting(Me, New TranPlanRowChangeEvent(CType(e.Row,TranPlanRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveTranPlanRow(ByVal row As TranPlanRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class TranPlanRow
        Inherits DataRow
        
        Private tableTranPlan As TranPlanDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableTranPlan = CType(Me.Table,TranPlanDataTable)
        End Sub
        
        Public Property CmpltTime As String
            Get
                Try 
                    Return CType(Me(Me.tableTranPlan.CmpltTimeColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("无法获取值，因为它是 DBNull。", e)
                End Try
            End Get
            Set
                Me(Me.tableTranPlan.CmpltTimeColumn) = value
            End Set
        End Property
        
        Public Property DepartureTime As String
            Get
                Try 
                    Return CType(Me(Me.tableTranPlan.DepartureTimeColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("无法获取值，因为它是 DBNull。", e)
                End Try
            End Get
            Set
                Me(Me.tableTranPlan.DepartureTimeColumn) = value
            End Set
        End Property
        
        Public Property Destination As String
            Get
                Try 
                    Return CType(Me(Me.tableTranPlan.DestinationColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("无法获取值，因为它是 DBNull。", e)
                End Try
            End Get
            Set
                Me(Me.tableTranPlan.DestinationColumn) = value
            End Set
        End Property
        
        Public Property InitialPlace As String
            Get
                Try 
                    Return CType(Me(Me.tableTranPlan.InitialPlaceColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("无法获取值，因为它是 DBNull。", e)
                End Try
            End Get
            Set
                Me(Me.tableTranPlan.InitialPlaceColumn) = value
            End Set
        End Property
        
        Public Property Note As String
            Get
                Try 
                    Return CType(Me(Me.tableTranPlan.NoteColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("无法获取值，因为它是 DBNull。", e)
                End Try
            End Get
            Set
                Me(Me.tableTranPlan.NoteColumn) = value
            End Set
        End Property
        
        Public Property TranCost As Integer
            Get
                Try 
                    Return CType(Me(Me.tableTranPlan.TranCostColumn),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("无法获取值，因为它是 DBNull。", e)
                End Try
            End Get
            Set
                Me(Me.tableTranPlan.TranCostColumn) = value
            End Set
        End Property
        
        Public Property TranOrderFormNO As Integer
            Get
                Return CType(Me(Me.tableTranPlan.TranOrderFormNOColumn),Integer)
            End Get
            Set
                Me(Me.tableTranPlan.TranOrderFormNOColumn) = value
            End Set
        End Property
        
        Public Property TranPlanNO As Integer
            Get
                Return CType(Me(Me.tableTranPlan.TranPlanNOColumn),Integer)
            End Get
            Set
                Me(Me.tableTranPlan.TranPlanNOColumn) = value
            End Set
        End Property
        
        Public Property TransitRoute As String
            Get
                Try 
                    Return CType(Me(Me.tableTranPlan.TransitRouteColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("无法获取值，因为它是 DBNull。", e)
                End Try
            End Get
            Set
                Me(Me.tableTranPlan.TransitRouteColumn) = value
            End Set
        End Property
        
        Public Property VehicleNO As Integer
            Get
                Return CType(Me(Me.tableTranPlan.VehicleNOColumn),Integer)
            End Get
            Set
                Me(Me.tableTranPlan.VehicleNOColumn) = value
            End Set
        End Property
        
        Public Function IsCmpltTimeNull() As Boolean
            Return Me.IsNull(Me.tableTranPlan.CmpltTimeColumn)
        End Function
        
        Public Sub SetCmpltTimeNull()
            Me(Me.tableTranPlan.CmpltTimeColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDepartureTimeNull() As Boolean
            Return Me.IsNull(Me.tableTranPlan.DepartureTimeColumn)
        End Function
        
        Public Sub SetDepartureTimeNull()
            Me(Me.tableTranPlan.DepartureTimeColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsDestinationNull() As Boolean
            Return Me.IsNull(Me.tableTranPlan.DestinationColumn)
        End Function
        
        Public Sub SetDestinationNull()
            Me(Me.tableTranPlan.DestinationColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsInitialPlaceNull() As Boolean
            Return Me.IsNull(Me.tableTranPlan.InitialPlaceColumn)
        End Function
        
        Public Sub SetInitialPlaceNull()
            Me(Me.tableTranPlan.InitialPlaceColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsNoteNull() As Boolean
            Return Me.IsNull(Me.tableTranPlan.NoteColumn)
        End Function
        
        Public Sub SetNoteNull()
            Me(Me.tableTranPlan.NoteColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsTranCostNull() As Boolean
            Return Me.IsNull(Me.tableTranPlan.TranCostColumn)
        End Function
        
        Public Sub SetTranCostNull()
            Me(Me.tableTranPlan.TranCostColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsTransitRouteNull() As Boolean
            Return Me.IsNull(Me.tableTranPlan.TransitRouteColumn)
        End Function
        
        Public Sub SetTransitRouteNull()
            Me(Me.tableTranPlan.TransitRouteColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class TranPlanRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As TranPlanRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As TranPlanRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As TranPlanRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
